baseurl:
title: Through the Eyes of Suminda
subtitle: The world as I see it
author: Suminda Sirinath Salpitikorala Dharmasena
simple_search: http://google.com/search
description: A Jekyll theme for content-rich sites
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: Asia/Colombo
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
# Google Analytics
google_analytics: G-2PGJ0112G4
# Google Ads
google_ad_format: autorelaxed
google_ad_client: 0000000000000000
google_ad_slot: 00000000
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
